### PR TITLE
#11 add pre process to resize images in build.

### PR DESCRIPTION
**Pull request by gkmngrgn**
## Description

- updated versions of `gatsby-transformer-sharp` and `gatsby-plugin-sharp`.
- add pre process to resize images in build.
- correct indentations in component files.

## Motivation and context

I've no motivation, I hate JS.

## How to test

just run `gatsby deploy` and disable max-width and max-height features of img style.

## Screenshots

image

### CODE REVIEW

**Comment by gkmngrgn** [comment]
@eralpkaraduman do we use netlify build? If so, can you adapt this solution?

https://github.com/gatsbyjs/gatsby/issues/20698#issuecomment-576353427

**Comment by eralpkaraduman** [comment]
> @eralpkaraduman do we use netlify build? If so, can you adapt this solution?
> 
> [gatsbyjs/gatsby#20698 (comment)](https://github.com/gatsbyjs/gatsby/issues/20698#issuecomment-576353427)

let's try `rm -rf node_modules` `rm package-lock.json` `npm i` first, so we try updating the dependency tree. I assume vips installed on ci machine is not matching the one we require.
Builds go faster if we don't ignore the vips installed on netlifys machines

**Comment by eralpkaraduman** [comment]
Suggesting this change;
updated subdependencies and downgraded sharp related ones.
You can merge this PR onto this PR to get CD working.
https://github.com/gkmngrgn/unhandledexception.club/pull/1

Tried CD on this PR, it was able to build on netlify properly
#27 see the checks at https://github.com/nicework-company/unhandledexception.club/pull/27/checks

**Review by eralpkaraduman — APPROVED** [review]
💎👌

**Pull request merged**
